### ISSUE TITLE
API package start error

### ISSUE THREAD

**Issue by vukovinski** [xxRockOnxx/ai-upscaler#1]
I'm getting an error when starting the API package on Windows with the LTS version of Node:

Cannot find ..\build\Release\magic

I haven't seen a mention of magic anywhere in the docs, maybe some step to run locally is missing from the docs?

```
PS C:\Users\Administrator.SV_SRV\Desktop\Binary\ai-upscaler\packages\api> yarn start
yarn run v1.22.19
warning package.json: No license field
$ npx ts-node -r dotenv/config -T src/main.ts
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Error: Cannot find module '../build/Release/magic'
Require stack:
- C:\Users\Administrator.SV_SRV\Desktop\Binary\ai-upscaler\packages\api\node_modules\mmmagic\lib\index.js
- C:\Users\Administrator.SV_SRV\Desktop\Binary\ai-upscaler\packages\api\src\http\post-submit.ts
- C:\Users\Administrator.SV_SRV\Desktop\Binary\ai-upscaler\packages\api\src\main.ts
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\Administrator.SV_SRV\Desktop\Binary\ai-upscaler\packages\api\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Administrator.SV_SRV\Desktop\Binary\ai-upscaler\packages\api\node_modules\mmmagic\lib\index.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\Administrator.SV_SRV\Desktop\Binary\ai-upscaler\packages\api\node_modules\ts-node\src\index.ts:1587:43)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Administrator.SV_SRV\\Desktop\\Binary\\ai-upscaler\\packages\\api\\node_modules\\mmmagic\\lib\\index.js',
    'C:\\Users\\Administrator.SV_SRV\\Desktop\\Binary\\ai-upscaler\\packages\\api\\src\\http\\post-submit.ts',
    'C:\\Users\\Administrator.SV_SRV\\Desktop\\Binary\\ai-upscaler\\packages\\api\\src\\main.ts'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vukovinski** [comment]
The UI and Worker packages start up fine

**Comment by vukovinski** [comment]
Looks like a problem with mmmagic itself

https://github.com/mscdex/mmmagic/issues/11

**Comment by vukovinski** [comment]
Fix for Windows:

```
cd packages\api\node_modules\mmmagic
yarn install
```

which will rebuild the mmmagic .c files, and then start the API package as usual

**Comment by xxRockOnxx** [comment]
Hi. Although you seem to already figure out this issue, I'm replying to let you know this is an active repo and I will try to help whenever I can. Feel free to let me know of any more issues you might encounter.
